name: training-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - pandas
  - numpy
  - scipy
  - pywavelets 
  - pip
  - scikit-learn
  - matplotlib
  - seaborn
  - sktime # for rocket
  - pyts # for rocket
  - numba # for rocket
  - pingouin
  - pip: 
    - nolds
